x-plane:
  connection:
    serial:
      device: /dev/tty.usbserial-31230 #tty.usbserial-144420
      baud: 9600
      timeout: 5
    webapi:
      url: http://localhost:8086/api/v2
      message_rate: 10  # Process every 10th message
